version: "3.7"
services:
  app:
    build:
      args:
        user: student
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: adileg/pp2_group_6
    ports: - "80:80"
    container_name: laravel-docker
    restart: always
    working_dir: /PP2_group6/pp2_group6